config/routes.rb
Rails.application.routes.draw do
  resources :news_ratings
  resources :orgs
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :news_sources
  resources :news_categories
  get 'about', to: 'about#show'

  resources :mes_trucs
  get 'home/index'
  root 'news_sources#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/org.rb
class Org < ApplicationRecord
  resourcify

  has_many :memberships, dependent: :delete_all
  has_many :users, through: :memberships

  has_many :org_ratings, dependent: :delete_all
  has_many :news_sources, through: :org_ratings

  has_many :org_descriptions
  accepts_nested_attributes_for :org_descriptions, :allow_destroy => true

  validates :name, presence: true

end

app/controllers/orgs_controller.rb
class OrgsController < ApplicationController
  before_action :set_org, only: [:show, :edit, :update, :destroy]

  # GET /orgs
  # GET /orgs.json
  def index
    @orgs = Org.paginate(:page => params[:page], per_page: 5)
  end

  # GET /orgs/1
  # GET /orgs/1.json
  def show
  end

  # GET /orgs/new
  def new
    @org = Org.new
  end

  # GET /orgs/1/edit
  def edit
  end

  # POST /orgs
  # POST /orgs.json
  def create
    @org = Org.new(org_params)

    respond_to do |format|
      if @org.save
        format.html { redirect_to @org, notice: 'Org was successfully created.' }
        format.json { render :show, status: :created, location: @org }
      else
        format.html { render :new }
        format.json { render json: @org.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orgs/1
  # PATCH/PUT /orgs/1.json
  def update
    respond_to do |format|
      if @org.update(org_params)
        format.html { redirect_to @org, notice: 'Org was successfully updated.' }
        format.json { render :show, status: :ok, location: @org }
      else
        format.html { render :edit }
        format.json { render json: @org.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orgs/1
  # DELETE /orgs/1.json
  def destroy
    @org.destroy
    respond_to do |format|
      format.html { redirect_to orgs_url, notice: 'Org was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_org
      @org = Org.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def org_params
      params.require(:org).permit(:name, :org_descriptions_attributes => [:id, :lang, :description, :_destroy])
    end
end

app/helpers/orgs_helper.rb
module OrgsHelper
end

app/views/orgs/_form.html.haml
= simple_form_for(@org) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

    = field_set_tag 'Description' do
      .container
        - @org.org_descriptions.each do |d|
          = render 'org_descriptions_form', :f => f, :d => d
        .row
          &nbsp;
        = link_to_add_fields "Add description", f, :org_descriptions

  .form-actions
    = f.button :submit

app/views/orgs/_org_descriptions_form.html.haml
.row
  = f.simple_fields_for 'org_descriptions_attributes[]', d do |df|
    .col-sm-2
      = df.input :id, as: :hidden
      = df.input :lang
    .col-sm-8
      = df.input :description
    .col-sm-2.destroy
      = df.input :_destroy, as: :hidden
      = button_tag 'Delete', :type => 'button', :class => 'btn btn-danger remove_fields'

app/views/orgs/edit.html.haml
%h1 Editing org

= render 'form'

= link_to 'Show', @org
\|
= link_to 'Back', orgs_path

app/views/orgs/index.html.haml
-#
  Used when listing (index) all Organizations
- model_class = Org
- provide(:title, model_class.model_name.human.pluralize.titleize)

.page-header
  %h1=t '.title', default: model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= t :name, default: model_class.human_attribute_name(:name)
      %th= t :membership, default: 'Members*'
      %th=t '.actions', default: t("helpers.actions")
  %tbody

  %tbody
    - @orgs.each do |org|
      %tr
        %td= org.name
        %td
          - if can? :registrar, org
            %em{:style => "color:red;"}
              = org.users.count
          - else
            = org.users.count
        %td
          -if can? :read, org
            = link_to org_path(org), class: 'btn btn-xs', title: "#{ t('.show', default: t('helpers.links.show')) }" do
              = glyph 'info-sign'
          -if can? :update, org
            = link_to edit_org_path(org), class: 'btn btn-xs', title: "#{ t('.edit', default: t('helpers.links.edit')) }" do
              = glyph 'pencil'
          -if can? :manage, org
            = link_to org_path(org), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-xs', title: "#{ t('.destroy', default: t('helpers.links.destroy')) }" do
              = glyph 'remove'

-if can? :manage, @orgs
  = link_to t('.new', default: t("helpers.links.new")), new_org_path, class: 'btn btn-primary'
%br

.nav(aria-label="page navigating")
  = will_paginate @orgs, renderer: BootstrapPagination::Rails, class:"pagination-sm"

app/views/orgs/new.html.haml
%h1 New org

= render 'form'

= link_to 'Back', orgs_path

app/views/orgs/show.html.haml
- model_class = Org
- provide(:title, model_class.model_name.human)

.page-header
  //%h1=t '.title', default: model_class.model_name.human.titleize
  %h1=model_class.model_name.human
  #notice= notice
.fieldset
  %dl
    %dt.label.label-default= model_class.human_attribute_name(:name)
    %dd
      %pre.prettyprint= @org.name

  -# Handle org_descriptions
  - if @org.org_descriptions.user_locale.count > 0 then
    %dl
      %dt.label.label-default Description
      %dd
        %pre.prettyprint=@org.org_descriptions.user_locale.first.description
  - elsif @org.org_descriptions.default_locale.count > 0 then
    %dl
      %dt.label.label-default Description
      %dd
        %pre.prettyprint=@org.org_descriptions.default_locale.first.description
  - elsif @org.org_descriptions.count > 0 then
    %dl
      %dt.label.label-default Description
      %dd
        %pre.prettyprint=@org.org_descriptions.first.description
  - else
    %pre.prettyprint No Description is available for this organization.

  -if can? :read, Membership
    %dl
      %dt.label.label-default
        - if can? :registrar, @org
          %em{:style => "color:red;"}
            = model_class.human_attribute_name(:memberships)
        - else
          = model_class.human_attribute_name(:memberships)
      %dd
        %ul
          - @org.memberships.each do |member|
            %li
              =member.user.name
              %span.badge=member.credibility


.form-group
  = link_to  orgs_path, class: 'btn btn-default' do
    = t('.back', default: t("helpers.links.back"))
    = glyph 'chevron-left'

  - if can? :update, @orgs
    = link_to edit_org_path(@org), class: 'btn btn-default' do
      = t('.edit', default: t("helpers.links.edit"))
      = glyph 'pencil'
  &nbsp;
  - if can? :manage, @orgs
    = link_to t('.destroy', default: t("helpers.links.destroy")), news_sources_path(@news_source), method: "delete", data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-danger'