config/routes.rb
Rails.application.routes.draw do
  resources :news_ratings
  resources :orgs
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :news_sources
  resources :news_categories
  get 'about', to: 'about#show'

  resources :mes_trucs
  get 'home/index'
  root 'news_sources#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/mes_truc.rb
class MesTruc < ApplicationRecord
  resourcify
  validates :title, presence: true
  validates :artist, presence: true
end

app/controllers/mes_trucs_controller.rb
class MesTrucsController < ApplicationController
  #before_action :set_mes_truc, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to mes_trucs_path, :alert => exception.message
  end

  # GET /mes_trucs
  # GET /mes_trucs.json
  def index
    @mes_trucs = MesTruc.paginate(:page => params[:page], per_page: 5)
    puts "index /mes_trucs"
  end

  # GET /mes_trucs/1
  # GET /mes_trucs/1.json
  def show
    puts "show /mes_trucs"
  end

  # GET /mes_trucs/new
  def new
    @mes_truc = MesTruc.new
  end

  # GET /mes_trucs/1/edit
  def edit
  end

  # POST /mes_trucs
  # POST /mes_trucs.json
  def create
    @mes_truc = MesTruc.new(mes_truc_params)

    respond_to do |format|
      if @mes_truc.save
        format.html { redirect_to @mes_truc, notice: 'Mes truc was successfully created.' }
        format.json { render :show, status: :created, location: @mes_truc }
      else
        format.html { render :new }
        format.json { render json: @mes_truc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mes_trucs/1
  # PATCH/PUT /mes_trucs/1.json
  def update
    respond_to do |format|
      if @mes_truc.update(mes_truc_params)
        format.html { redirect_to @mes_truc, notice: 'Mes truc was successfully updated.' }
        format.json { render :show, status: :ok, location: @mes_truc }
      else
        format.html { render :edit }
        format.json { render json: @mes_truc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mes_trucs/1
  # DELETE /mes_trucs/1.json
  def destroy
    @mes_truc.destroy
    respond_to do |format|
      format.html { redirect_to mes_trucs_url, notice: 'Mes truc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mes_truc
      @mes_truc = MesTruc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mes_truc_params
      params.require(:mes_truc).permit(:title, :artist)
    end
end

app/helpers/mes_trucs_helper.rb
module MesTrucsHelper
end

app/views/mes_trucs/_form.html.haml
= simple_form_for(@mes_truc, validate: true) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :artist
  .form-actions
    = f.button :submit
  -#= link_to t('.cancel', default: t("helpers.links.cancel")), mes_trucs_path)

app/views/mes_trucs/edit.html.haml
- model_class = MesTruc
.page-header
  %h1=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize
= render partial: "form"

app/views/mes_trucs/index.html.haml
- provide(:title, 'Mes Trucs')
- model_class = MesTruc
.page-header
  %h1=t '.title', default: model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:artist)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', default: t("helpers.actions")
  %tbody
    - @mes_trucs.each do |mes_truc|
      %tr
        %td= mes_truc.id
        %td= mes_truc.title
        %td= mes_truc.artist
        //%td=l mes_truc.created_at, format: :long
        %td= mes_truc.created_at.iso8601(3)
        %td
          -if can? :read, mes_truc
            = link_to mes_truc_path(mes_truc), class: 'btn btn-xs', title: "#{ t('.show', default: t('helpers.links.show')) }" do
              = glyph 'info-sign'
          -if can? :update, mes_truc
            = link_to edit_mes_truc_path(mes_truc), class: 'btn btn-xs', title: "#{ t('.edit', default: t('helpers.links.edit')) }" do
              = glyph 'pencil'
          -if can? :manage, mes_truc
            = link_to mes_truc_path(mes_truc), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-xs', title: "#{ t('.destroy', default: t('helpers.links.destroy')) }" do
              = glyph 'remove'

= link_to t('.new', default: t("helpers.links.new")), new_mes_truc_path, class: 'btn btn-primary'
%br

.nav(aria-label="page navigating")
  = will_paginate @mes_trucs, renderer: BootstrapPagination::Rails, class:"pagination-sm"

app/views/mes_trucs/new.html.haml
- model_class = MesTruc
.page-header
  %h1=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize
= render partial: "form"

app/views/mes_trucs/show.html.haml
- model_class = MesTruc
.page-header
  %h1=t '.title', default: model_class.model_name.human.titleize
.fieldset
  %dl
    %dt.label.label-default= model_class.human_attribute_name(:title)
    %dd
      %pre.prettyprint= @mes_truc.title
    %dt.label.label-default= model_class.human_attribute_name(:artist)
    %dd
      %pre.prettyprint= @mes_truc.artist

.form-group
  = link_to  mes_trucs_path, class: 'btn btn-default' do
    = t('.back', default: t("helpers.links.back"))
    = glyph 'chevron-left'

  - if can? :update, @mes_truc
    = link_to edit_mes_truc_path(@mes_truc), class: 'btn btn-default' do
      = t('.edit', default: t("helpers.links.edit"))
      = glyph 'pencil'
  &nbsp;
  - if can? :manage, @mes_truc
    = link_to t('.destroy', default: t("helpers.links.destroy")), mes_truc_path(@mes_truc), method: "delete", data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-danger'