config/routes.rb
Rails.application.routes.draw do
  resources :news_ratings
  resources :orgs
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :news_sources
  resources :news_categories
  get 'about', to: 'about#show'

  resources :mes_trucs
  get 'home/index'
  root 'news_sources#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/news_category.rb
class NewsCategory < ApplicationRecord
  resourcify
  has_and_belongs_to_many :news_sources,
    :join_table => :news_categories_news_sources

  def self.tokens(query)
    tags = where("name like ?", "%#{query}%")
    if tags.empty?
      [{id: "<<<#{query}>>>", name: "New: \"#{query}\""}]
    else
      tags
    end
  end

  def self.ids_from_tokens(tokens)
    tokens.gsub!(/<<<(.+?)>>>/) { create!(name: $1).id }
    tokens.split(',')
  end
end

app/controllers/news_categories_controller.rb
class NewsCategoriesController < ApplicationController
  before_action :set_news_category, only: [:show, :edit, :update, :destroy]

  # GET /news_categories
  # GET /news_categories.json
  def index
    @news_categories = NewsCategory.order(:name)
    respond_to do |format|
      format.html
      format.json { render json: @news_categories.tokens(params[:q]) }
    end
  end

  # GET /news_categories/1
  # GET /news_categories/1.json
  def show
  end

  # GET /news_categories/new
  def new
    @news_category = NewsCategory.new
  end

  # GET /news_categories/1/edit
  def edit
  end

  # POST /news_categories
  # POST /news_categories.json
  def create
    @news_category = NewsCategory.new(news_category_params)

    respond_to do |format|
      if @news_category.save
        format.html { redirect_to @news_category, notice: 'News category was successfully created.' }
        format.json { render :show, status: :created, location: @news_category }
      else
        format.html { render :new }
        format.json { render json: @news_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news_categories/1
  # PATCH/PUT /news_categories/1.json
  def update
    respond_to do |format|
      if @news_category.update(news_category_params)
        format.html { redirect_to @news_category, notice: 'News category was successfully updated.' }
        format.json { render :show, status: :ok, location: @news_category }
      else
        format.html { render :edit }
        format.json { render json: @news_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_categories/1
  # DELETE /news_categories/1.json
  def destroy
    @news_category.destroy
    respond_to do |format|
      format.html { redirect_to news_categories_url, notice: 'News category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news_category
      @news_category = NewsCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_category_params
      params.require(:news_category).permit(:name)
    end
end

app/helpers/news_categories_helper.rb
module NewsCategoriesHelper
end

app/views/news_categories/_form.html.haml
= form_for @news_category do |f|
  - if @news_category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@news_category.errors.count, "error")} prohibited this news_category from being saved:"
      %ul
        - @news_category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/news_categories/edit.html.haml
%h1 Editing news_category

= render 'form'

= link_to 'Show', @news_category
\|
= link_to 'Back', news_categories_path

app/views/news_categories/index.html.haml
%h1 Listing news_categories

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @news_categories.each do |news_category|
      %tr
        %td= news_category.name
        %td= link_to 'Show', news_category
        %td= link_to 'Edit', edit_news_category_path(news_category)
        %td= link_to 'Destroy', news_category, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New News category', new_news_category_path

app/views/news_categories/new.html.haml
%h1 New news_category

= render 'form'

= link_to 'Back', news_categories_path

app/views/news_categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @news_category.name

= link_to 'Edit', edit_news_category_path(@news_category)
\|
= link_to 'Back', news_categories_path