config/routes.rb
Rails.application.routes.draw do
  resources :news_ratings
  resources :orgs
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :news_sources
  resources :news_categories
  get 'about', to: 'about#show'

  resources :mes_trucs
  get 'home/index'
  root 'news_sources#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.haml
%footer.footer
  .container
    .row
      .col-sm-8.col-md-6
        %small.nav.navbar-nav
          Is It True by Meetrical (
          = $deploy_version
          ) — &copy; 2016 Meetrical inc.
      .col-sm-4.col-md-6
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "About",   about_path
          %li= link_to "Contact", root_path

    .row
      %p &nbsp;

app/views/layouts/_header.html.haml
%header.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
  / navbar starts here *
  .navbar-header
    %button.navbar-inverse.navbar-toggle{"data-target" => ".navbar-ex1-collapse", "data-toggle" => "collapse", :type => "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to (t "site_name", default:"Is it true?"), root_path, id: "logo"
  / navbar-header
  .navbar-collapse.navbar-inverse.collapse.navbar-ex1-collapse
    %ul.nav.navbar-nav.navbar-left
      %li= link_to (t "home"), root_path
      %li= render 'layouts/resources'

    %ul.nav.navbar-nav.navbar-right
      - if user_signed_in?
        - if can? :access, :rails_admin
          %li=link_to (t 'nav.admin', default:"Admin"), rails_admin_path
        %li= link_to  (t 'nav.edit', default:"Edit profile"),  edit_user_registration_path
        %li= link_to  (t 'nav.logout', default:"Logout"),  destroy_user_session_path, :method => :delete
      - else
        %li=link_to   (t 'nav.login', default:"Log in!"), new_user_session_path

      %li= render 'layouts/locale_selector', controller: controller_name, action: action_name

=# link_to "Is it true?", root_path, id: "logo"

app/views/layouts/_locale_selector.html.haml
%li#fat-menu.dropdown
  %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
    //= t('.language')
    %span.fa.fa-lg.fa-globe
    %b.caret
  %ul.dropdown-menu
    - previous_enabled = true
    - locale_languages.each do |language|
      - if language[:disabled]
        - if previous_enabled
          - previous_enabled = false
          %li.divider

        %li.disabled
          = link_to language[:label],
                    controller: controller,
                    action: action,
                    set_locale: language[:locale],
                    page: params[:page]
      - else
        %li
          = link_to language[:label],
                    controller: controller,
                    action: action,
                    set_locale: language[:locale],
                    page: params[:page]

app/views/layouts/_resources.html.haml
%li.dropdown
  %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
    //= t('.language')
    = t 'nav.resources', default:'Resources'
    %b.caret
  %ul.dropdown-menu
    %li= link_to MesTruc.model_name.human(:count => 2),  mes_trucs_path
    %li= link_to NewsSource.model_name.human(:count => 2), news_sources_path
    %li= link_to Org.model_name.human(:count => 2), orgs_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>

app/views/layouts/application.html.haml
!!! 5
/[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en">
/[if IE 7] <html class="no-js lt-ie9 lt-ie8" lang="en">
/[if IE 8] <html class="no-js lt-ie9 " lang="en">
<!--[if gt IE 8]><!-->
%html.no-js{:lang => "en"}
  <!--<![endif]-->
  %head
    /Our site uses UTF8 (Unicode)
    %meta{:content => "text/html; charset=UTF-8", |
          "http-equiv" => "Content-Type"}/
    %meta{:charset => 'utf-8' }/

    /And it supports Android or iPhone as well
    %meta{:content => "width=device-width, user-scalable=yes", |
          :name => "viewport"}/

    %title= full_title(yield(:title))

    / Modernizr helps to keep the site compatible with older browers
    = javascript_include_tag :modernizr
    = stylesheet_link_tag "https://fonts.googleapis.com/css?family=Black+Ops+One&subset=latin-ext"
    / The styles needed by the application
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'

    / And the javascript
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    = javascript_include_tag 'https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js'
    = javascript_include_tag 'https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js'
    = stylesheet_link_tag 'https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css'

    / Keep forgery away
    = csrf_meta_tags

    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-85597904-1', 'auto');
      ga('send', 'pageview');


  %body
    /Warns Internet Explorer (Microsoft) < 7 is too old for this site
    /[if lt IE 7] <p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p>
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        %div{:class => "alert alert-#{message_type}"}= message
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?